remote: true

experienceLevel:
  internship: false
  entry: false
  associate: false
  mid-senior level: true
  director: true
  executive: true

jobTypes:
  full-time: true
  contract: true
  part-time: false
  temporary: false
  internship: false
  other: false
  volunteer: false

date:
  all time: false
  month: true
  week: true
  24 hours: true

positions:
  - AI Manager

locations:
  - London

apply_once_at_company: false

distance: 50

company_blacklist:
  - Accenture
  - BCG
  - BenchSci
  - Deloitte
  - EY
  - FlutterFlow
  - IQVIA
  - Loblaw
  - MNP
  - PWC
  - Santis Health
  - Shoppers Drug Mart

title_blacklist:
  - analyst
  - technician
  - software
  - specialist
  - sales
  - architect
  - engineer
  - developer
  - teacher
  - therapist
  - veterinarian
  - pathologist
  - optometrist
  - accountant
  - realtor
  - construction
  - restaurant
  - kitchen
  - dental
  -  nursing
  - nurse
  - cook
  - attorney
  - psychiatrist
  - physician
  - intern
  - EY
  - KPMG
  - PWC
  - Deloitte
  - Accenture
  - PSW
  - compliance
  - legal
  - security

job_applicants_threshold:
  min_applicants: 0
  max_applicants: 300

llm_model_type: gemini
llm_model: 'gemini-pro'
# llm_api_url: 'https://api.pawan.krd/cosmosrp/v1'